Feature: viewing requests as a user

Scenario Outline: Viewing requests as employee
	Given 
	When
	And
	Then
	
	Examples:
		|						|						|
		|						|						|
		|						|						|
		
Scenario Outline: Viewing requests as supervisor
	Given 
	When
	And
	Then
	
	Examples:
		|						|						|
		|						|						|
		|						|						|
		
Scenario Outline: Viewing requests as dept head
	Given 
	When
	And
	Then
	
	Examples:
		|						|						|
		|						|						|
		|						|						|
		
Scenario Outline: Viewing requests as Benco
	Given 
	When
	And
	Then
	
	Examples:
		|						|						|
		|						|						|
		|						|						|
		